spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-34-247-118-233.eu-west-1.compute.amazonaws.com:5432/d4o8nhbt4looog
    username: ongvhnvhoajzpq
    password: 4927bb7c73385f909d9d544d592283d98086cc404189c8edeb86df5d63ff7f31
    pool-size: 30
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true