spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-34-247-118-233.eu-west-1.compute.amazonaws.com:5432/dc1dgpg8unare6
    username: jgyhovnggyhrgn
    password: 5dff12c3bb0562f46045a00f8074d4e5e670333476ae4c01416765d981a4ef92
    pool-size: 30
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true